CREATE TABLE IF NOT EXISTS b24_custom_entity (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CRM_ENTITY_ID INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DATE_CREATE DATETIME DEFAULT CURRENT_TIMESTAMP
    );
